// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 06/10/2024 21:33:00
const configMerger = require("C:/Users/Gary/Documents/Projets/nuxtjs-tailwind-blog/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Gary/Documents/Projets/nuxtjs-tailwind-blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Gary/Documents/Projets/nuxtjs-tailwind-blog/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Gary/Documents/Projets/nuxtjs-tailwind-blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Gary/Documents/Projets/nuxtjs-tailwind-blog/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Gary/Documents/Projets/nuxtjs-tailwind-blog/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Gary/Documents/Projets/nuxtjs-tailwind-blog/plugins/**/*.{js,ts,mjs}","C:/Users/Gary/Documents/Projets/nuxtjs-tailwind-blog/composables/**/*.{js,ts,mjs}","C:/Users/Gary/Documents/Projets/nuxtjs-tailwind-blog/utils/**/*.{js,ts,mjs}","C:/Users/Gary/Documents/Projets/nuxtjs-tailwind-blog/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Gary/Documents/Projets/nuxtjs-tailwind-blog/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Gary/Documents/Projets/nuxtjs-tailwind-blog/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["23"] = "C:/Users/Gary/Documents/Projets/nuxtjs-tailwind-blog/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
